/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Dimension;
import java.awt.Graphics;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Maria
 */
public class OriginPanel extends javax.swing.JPanel {
    private File fileImage;
    private ImageIcon image;
    /**
     * Creates new form OriginPanel
     */
    public OriginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        UploadItem = new javax.swing.JMenuItem();

        UploadItem.setText("Upload");
        UploadItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadItemActionPerformed(evt);
            }
        });
        jPopupMenu.add(UploadItem);

        setPreferredSize(new java.awt.Dimension(500, 520));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseReleased

    private void UploadItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadItemActionPerformed
        int resultado;

        UploadImage uploadWindow = new UploadImage();

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");

        uploadWindow.jFileChooser.setFileFilter(filtro);

        resultado = uploadWindow.jFileChooser.showOpenDialog(null);

        if (JFileChooser.APPROVE_OPTION == resultado) {

            fileImage = uploadWindow.jFileChooser.getSelectedFile();

            try {
                image = new ImageIcon(fileImage.toString());
                repaint();

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "Error uploading image 1002 " + ex);

            }
        } else if (JFileChooser.CANCEL_OPTION == resultado) {
            JOptionPane.showMessageDialog(null, "Cancelled",
                    "",
                    JOptionPane.OK_OPTION);

        }
    }//GEN-LAST:event_UploadItemActionPerformed

    public void paintComponent(Graphics g) {
        UploadImage uploadWindow = new UploadImage();
        Dimension size = getSize();
        fileImage = uploadWindow.jFileChooser.getSelectedFile();

        try {
            if (image != null) {
                ImageIcon fondo = image;
                g.drawImage(fondo.getImage(), 0, 0, size.width, size.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Error uploading image 1001 " + ex);

        }
        
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem UploadItem;
    private javax.swing.JPopupMenu jPopupMenu;
    // End of variables declaration//GEN-END:variables
}
